name: Run Postman Collection

on:
  push:
    branches: [ "main" ]  # Change this to your main branch name
  pull_request:
    branches: [ "main" ]

#Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create dir
        run: |
          mkdir SampleArtifact
  

      - name: Install Node
        uses: actions/checkout@v2
        with:
          node-version: ' v20.11.1.'
          
      - name: Install Newman
        run: |
          npm install -g newman@6.1.2
          npm install -g newman-reporter-htmlextra

      #Run Collection
      - name: Execute Postman Collection
        run: |
          #newman run Expense_Tracker_2024.postman_collection -e path/to/your/environment.json -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html  
          newman run "Newman/Expense_Tracker_2024.postman_collection" --export-collection collection.json -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html 


      #Publish the report
      - name: Publish Report
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: SampleArtifact
       
